# generated from genmsg/cmake/pkg-genmsg.context.in

messages_str = "/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/msg/YoloDetectionInfo.msg;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/msg/GoalDescription.msg;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/msg/LockonSpeedControl.msg;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/msg/LockonSpeedControl.msg;/home/nvidia/Desktop/roboinTX2/devel/share/icra_roboin_msgs/msg/YoloDetectionAction.msg;/home/nvidia/Desktop/roboinTX2/devel/share/icra_roboin_msgs/msg/YoloDetectionActionGoal.msg;/home/nvidia/Desktop/roboinTX2/devel/share/icra_roboin_msgs/msg/YoloDetectionActionResult.msg;/home/nvidia/Desktop/roboinTX2/devel/share/icra_roboin_msgs/msg/YoloDetectionActionFeedback.msg;/home/nvidia/Desktop/roboinTX2/devel/share/icra_roboin_msgs/msg/YoloDetectionGoal.msg;/home/nvidia/Desktop/roboinTX2/devel/share/icra_roboin_msgs/msg/YoloDetectionResult.msg;/home/nvidia/Desktop/roboinTX2/devel/share/icra_roboin_msgs/msg/YoloDetectionFeedback.msg"
services_str = "/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/BlackboardGeneralInfo.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/BehaviorStyleSet.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/SetGoal_2.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/SetEnemyPriority.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/RefereeHit.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/RefereeGameState.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/RefereeShoot.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/RefereeTag.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/RefereeBuff.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/RefereePenalty.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/RefereeReload.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/ConfirmHit.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/AmmoConsume.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/YawGain.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/PitchGain.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/XYOffset.srv;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/srv/ammo.srv"
pkg_name = "icra_roboin_msgs"
dependencies_str = "std_msgs;geometry_msgs;nav_msgs;actionlib_msgs"
langs = "gencpp;geneus;genlisp;gennodejs;genpy"
dep_include_paths_str = "icra_roboin_msgs;/home/nvidia/Desktop/roboinTX2/src/icra_roboin_msgs/msg;icra_roboin_msgs;/home/nvidia/Desktop/roboinTX2/devel/share/icra_roboin_msgs/msg;std_msgs;/opt/ros/kinetic/share/std_msgs/cmake/../msg;geometry_msgs;/opt/ros/kinetic/share/geometry_msgs/cmake/../msg;nav_msgs;/opt/ros/kinetic/share/nav_msgs/cmake/../msg;actionlib_msgs;/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg"
PYTHON_EXECUTABLE = "/usr/bin/python"
package_has_static_sources = '' == 'TRUE'
genmsg_check_deps_script = "/opt/ros/kinetic/share/genmsg/cmake/../../../lib/genmsg/genmsg_check_deps.py"
