(cl:defpackage icra_roboin_msgs-srv
  (:use )
  (:export
   "BLACKBOARDGENERALINFO"
   "<BLACKBOARDGENERALINFO-REQUEST>"
   "BLACKBOARDGENERALINFO-REQUEST"
   "<BLACKBOARDGENERALINFO-RESPONSE>"
   "BLACKBOARDGENERALINFO-RESPONSE"
  ))

