(cl:defpackage icra_roboin_msgs-msg
  (:use )
  (:export
   "<GOALDESCRIPTION>"
   "GOALDESCRIPTION"
   "<LOCKONSPEEDCONTROL>"
   "LOCKONSPEEDCONTROL"
   "<YOLODETECTIONACTION>"
   "YOLODETECTIONACTION"
   "<YOLODETECTIONACTIONFEEDBACK>"
   "YOLODETECTIONACTIONFEEDBACK"
   "<YOLODETECTIONACTIONGOAL>"
   "YOLODETECTIONACTIONGOAL"
   "<YOLODETECTIONACTIONRESULT>"
   "YOLODETECTIONACTIONRESULT"
   "<YOLODETECTIONFEEDBACK>"
   "YOLODETECTIONFEEDBACK"
   "<YOLODETECTIONGOAL>"
   "YOLODETECTIONGOAL"
   "<YOLODETECTIONINFO>"
   "YOLODETECTIONINFO"
   "<YOLODETECTIONRESULT>"
   "YOLODETECTIONRESULT"
  ))

