// Generated by gencpp from file icra_roboin_msgs/AmmoConsume.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_AMMOCONSUME_H
#define ICRA_ROBOIN_MSGS_MESSAGE_AMMOCONSUME_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/AmmoConsumeRequest.h>
#include <icra_roboin_msgs/AmmoConsumeResponse.h>


namespace icra_roboin_msgs
{

struct AmmoConsume
{

typedef AmmoConsumeRequest Request;
typedef AmmoConsumeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AmmoConsume
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::AmmoConsume > {
  static const char* value()
  {
    return "5a21dae1d703fd52723eaf9cba0ba9be";
  }

  static const char* value(const ::icra_roboin_msgs::AmmoConsume&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::AmmoConsume > {
  static const char* value()
  {
    return "icra_roboin_msgs/AmmoConsume";
  }

  static const char* value(const ::icra_roboin_msgs::AmmoConsume&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::AmmoConsumeRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::AmmoConsume > 
template<>
struct MD5Sum< ::icra_roboin_msgs::AmmoConsumeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::AmmoConsume >::value();
  }
  static const char* value(const ::icra_roboin_msgs::AmmoConsumeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::AmmoConsumeRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::AmmoConsume > 
template<>
struct DataType< ::icra_roboin_msgs::AmmoConsumeRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::AmmoConsume >::value();
  }
  static const char* value(const ::icra_roboin_msgs::AmmoConsumeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::AmmoConsumeResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::AmmoConsume > 
template<>
struct MD5Sum< ::icra_roboin_msgs::AmmoConsumeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::AmmoConsume >::value();
  }
  static const char* value(const ::icra_roboin_msgs::AmmoConsumeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::AmmoConsumeResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::AmmoConsume > 
template<>
struct DataType< ::icra_roboin_msgs::AmmoConsumeResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::AmmoConsume >::value();
  }
  static const char* value(const ::icra_roboin_msgs::AmmoConsumeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_AMMOCONSUME_H
