// Generated by gencpp from file icra_roboin_msgs/BehaviorStyleSet.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_BEHAVIORSTYLESET_H
#define ICRA_ROBOIN_MSGS_MESSAGE_BEHAVIORSTYLESET_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/BehaviorStyleSetRequest.h>
#include <icra_roboin_msgs/BehaviorStyleSetResponse.h>


namespace icra_roboin_msgs
{

struct BehaviorStyleSet
{

typedef BehaviorStyleSetRequest Request;
typedef BehaviorStyleSetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BehaviorStyleSet
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::BehaviorStyleSet > {
  static const char* value()
  {
    return "55497cc3dd55c5632392e3da32c9b591";
  }

  static const char* value(const ::icra_roboin_msgs::BehaviorStyleSet&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::BehaviorStyleSet > {
  static const char* value()
  {
    return "icra_roboin_msgs/BehaviorStyleSet";
  }

  static const char* value(const ::icra_roboin_msgs::BehaviorStyleSet&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::BehaviorStyleSetRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::BehaviorStyleSet > 
template<>
struct MD5Sum< ::icra_roboin_msgs::BehaviorStyleSetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::BehaviorStyleSet >::value();
  }
  static const char* value(const ::icra_roboin_msgs::BehaviorStyleSetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::BehaviorStyleSetRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::BehaviorStyleSet > 
template<>
struct DataType< ::icra_roboin_msgs::BehaviorStyleSetRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::BehaviorStyleSet >::value();
  }
  static const char* value(const ::icra_roboin_msgs::BehaviorStyleSetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::BehaviorStyleSetResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::BehaviorStyleSet > 
template<>
struct MD5Sum< ::icra_roboin_msgs::BehaviorStyleSetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::BehaviorStyleSet >::value();
  }
  static const char* value(const ::icra_roboin_msgs::BehaviorStyleSetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::BehaviorStyleSetResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::BehaviorStyleSet > 
template<>
struct DataType< ::icra_roboin_msgs::BehaviorStyleSetResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::BehaviorStyleSet >::value();
  }
  static const char* value(const ::icra_roboin_msgs::BehaviorStyleSetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_BEHAVIORSTYLESET_H
