// Generated by gencpp from file icra_roboin_msgs/BehaviorStyleSetRequest.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_BEHAVIORSTYLESETREQUEST_H
#define ICRA_ROBOIN_MSGS_MESSAGE_BEHAVIORSTYLESETREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace icra_roboin_msgs
{
template <class ContainerAllocator>
struct BehaviorStyleSetRequest_
{
  typedef BehaviorStyleSetRequest_<ContainerAllocator> Type;

  BehaviorStyleSetRequest_()
    : behavior(0)  {
    }
  BehaviorStyleSetRequest_(const ContainerAllocator& _alloc)
    : behavior(0)  {
  (void)_alloc;
    }



   typedef uint8_t _behavior_type;
  _behavior_type behavior;





  typedef boost::shared_ptr< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorStyleSetRequest_

typedef ::icra_roboin_msgs::BehaviorStyleSetRequest_<std::allocator<void> > BehaviorStyleSetRequest;

typedef boost::shared_ptr< ::icra_roboin_msgs::BehaviorStyleSetRequest > BehaviorStyleSetRequestPtr;
typedef boost::shared_ptr< ::icra_roboin_msgs::BehaviorStyleSetRequest const> BehaviorStyleSetRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_roboin_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'icra_roboin_msgs': ['/home/kimtaehan/Desktop/lets_go_canada/src/icra_roboin_msgs/msg', '/home/kimtaehan/Desktop/lets_go_canada/devel/share/icra_roboin_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "736276b219b2f8e79cd33bbc21236ebd";
  }

  static const char* value(const ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x736276b219b2f8e7ULL;
  static const uint64_t static_value2 = 0x9cd33bbc21236ebdULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_roboin_msgs/BehaviorStyleSetRequest";
  }

  static const char* value(const ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 behavior\n\
";
  }

  static const char* value(const ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.behavior);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehaviorStyleSetRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_roboin_msgs::BehaviorStyleSetRequest_<ContainerAllocator>& v)
  {
    s << indent << "behavior: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.behavior);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_BEHAVIORSTYLESETREQUEST_H
