// Generated by gencpp from file icra_roboin_msgs/BlackboardGeneralInfoResponse.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_BLACKBOARDGENERALINFORESPONSE_H
#define ICRA_ROBOIN_MSGS_MESSAGE_BLACKBOARDGENERALINFORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <geometry_msgs/PoseStamped.h>
#include <icra_roboin_msgs/GoalDescription.h>

namespace icra_roboin_msgs
{
template <class ContainerAllocator>
struct BlackboardGeneralInfoResponse_
{
  typedef BlackboardGeneralInfoResponse_<ContainerAllocator> Type;

  BlackboardGeneralInfoResponse_()
    : stamp()
    , time_passed_from_start(0)
    , game_state(0)
    , buff_zone_cooltime(0)
    , reload_zone_cooltime(0)
    , my_health(0)
    , is_hit(false)
    , which_armor_hit(0)
    , last_hit_time(0)
    , has_buff(false)
    , buff_left(0)
    , ammo(0)
    , my_pose()
    , enemy_pose1()
    , enemy_pose2()
    , how_many_enemies_detected(0)
    , is_enemy_1_detected(false)
    , is_enemy_2_detected(false)
    , locked_on_enemy(0)
    , enemy_priority(0)
    , goal()
    , current_behavior_style(0)
    , current_behavior_process(0)  {
    }
  BlackboardGeneralInfoResponse_(const ContainerAllocator& _alloc)
    : stamp()
    , time_passed_from_start(0)
    , game_state(0)
    , buff_zone_cooltime(0)
    , reload_zone_cooltime(0)
    , my_health(0)
    , is_hit(false)
    , which_armor_hit(0)
    , last_hit_time(0)
    , has_buff(false)
    , buff_left(0)
    , ammo(0)
    , my_pose(_alloc)
    , enemy_pose1(_alloc)
    , enemy_pose2(_alloc)
    , how_many_enemies_detected(0)
    , is_enemy_1_detected(false)
    , is_enemy_2_detected(false)
    , locked_on_enemy(0)
    , enemy_priority(0)
    , goal(_alloc)
    , current_behavior_style(0)
    , current_behavior_process(0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int32_t _time_passed_from_start_type;
  _time_passed_from_start_type time_passed_from_start;

   typedef uint8_t _game_state_type;
  _game_state_type game_state;

   typedef int32_t _buff_zone_cooltime_type;
  _buff_zone_cooltime_type buff_zone_cooltime;

   typedef int32_t _reload_zone_cooltime_type;
  _reload_zone_cooltime_type reload_zone_cooltime;

   typedef int16_t _my_health_type;
  _my_health_type my_health;

   typedef uint8_t _is_hit_type;
  _is_hit_type is_hit;

   typedef uint8_t _which_armor_hit_type;
  _which_armor_hit_type which_armor_hit;

   typedef int32_t _last_hit_time_type;
  _last_hit_time_type last_hit_time;

   typedef uint8_t _has_buff_type;
  _has_buff_type has_buff;

   typedef int32_t _buff_left_type;
  _buff_left_type buff_left;

   typedef int16_t _ammo_type;
  _ammo_type ammo;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _my_pose_type;
  _my_pose_type my_pose;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _enemy_pose1_type;
  _enemy_pose1_type enemy_pose1;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _enemy_pose2_type;
  _enemy_pose2_type enemy_pose2;

   typedef uint8_t _how_many_enemies_detected_type;
  _how_many_enemies_detected_type how_many_enemies_detected;

   typedef uint8_t _is_enemy_1_detected_type;
  _is_enemy_1_detected_type is_enemy_1_detected;

   typedef uint8_t _is_enemy_2_detected_type;
  _is_enemy_2_detected_type is_enemy_2_detected;

   typedef uint8_t _locked_on_enemy_type;
  _locked_on_enemy_type locked_on_enemy;

   typedef uint8_t _enemy_priority_type;
  _enemy_priority_type enemy_priority;

   typedef  ::icra_roboin_msgs::GoalDescription_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef uint8_t _current_behavior_style_type;
  _current_behavior_style_type current_behavior_style;

   typedef uint8_t _current_behavior_process_type;
  _current_behavior_process_type current_behavior_process;





  typedef boost::shared_ptr< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BlackboardGeneralInfoResponse_

typedef ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<std::allocator<void> > BlackboardGeneralInfoResponse;

typedef boost::shared_ptr< ::icra_roboin_msgs::BlackboardGeneralInfoResponse > BlackboardGeneralInfoResponsePtr;
typedef boost::shared_ptr< ::icra_roboin_msgs::BlackboardGeneralInfoResponse const> BlackboardGeneralInfoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_roboin_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'icra_roboin_msgs': ['/home/kimtaehan/Desktop/lets_go_canada/src/icra_roboin_msgs/msg', '/home/kimtaehan/Desktop/lets_go_canada/devel/share/icra_roboin_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5a6420e2d73a3b280e9fbf108fe64e9e";
  }

  static const char* value(const ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5a6420e2d73a3b28ULL;
  static const uint64_t static_value2 = 0x0e9fbf108fe64e9eULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_roboin_msgs/BlackboardGeneralInfoResponse";
  }

  static const char* value(const ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n\
int32 time_passed_from_start\n\
\n\
uint8 game_state\n\
int32 buff_zone_cooltime\n\
int32 reload_zone_cooltime\n\
int16 my_health\n\
bool is_hit\n\
uint8 which_armor_hit\n\
int32 last_hit_time\n\
bool has_buff\n\
int32 buff_left\n\
int16 ammo\n\
geometry_msgs/PoseStamped my_pose\n\
geometry_msgs/PoseStamped enemy_pose1\n\
geometry_msgs/PoseStamped enemy_pose2\n\
uint8 how_many_enemies_detected\n\
bool is_enemy_1_detected\n\
bool is_enemy_2_detected\n\
uint8 locked_on_enemy\n\
uint8 enemy_priority\n\
icra_roboin_msgs/GoalDescription goal\n\
uint8 current_behavior_style\n\
uint8 current_behavior_process\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: icra_roboin_msgs/GoalDescription\n\
std_msgs/Header header\n\
float64 x\n\
float64 y\n\
float64 yaw\n\
float64 xa\n\
float64 ya\n\
float64 yawa\n\
float64 etc\n\
";
  }

  static const char* value(const ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.time_passed_from_start);
      stream.next(m.game_state);
      stream.next(m.buff_zone_cooltime);
      stream.next(m.reload_zone_cooltime);
      stream.next(m.my_health);
      stream.next(m.is_hit);
      stream.next(m.which_armor_hit);
      stream.next(m.last_hit_time);
      stream.next(m.has_buff);
      stream.next(m.buff_left);
      stream.next(m.ammo);
      stream.next(m.my_pose);
      stream.next(m.enemy_pose1);
      stream.next(m.enemy_pose2);
      stream.next(m.how_many_enemies_detected);
      stream.next(m.is_enemy_1_detected);
      stream.next(m.is_enemy_2_detected);
      stream.next(m.locked_on_enemy);
      stream.next(m.enemy_priority);
      stream.next(m.goal);
      stream.next(m.current_behavior_style);
      stream.next(m.current_behavior_process);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlackboardGeneralInfoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_roboin_msgs::BlackboardGeneralInfoResponse_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "time_passed_from_start: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time_passed_from_start);
    s << indent << "game_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.game_state);
    s << indent << "buff_zone_cooltime: ";
    Printer<int32_t>::stream(s, indent + "  ", v.buff_zone_cooltime);
    s << indent << "reload_zone_cooltime: ";
    Printer<int32_t>::stream(s, indent + "  ", v.reload_zone_cooltime);
    s << indent << "my_health: ";
    Printer<int16_t>::stream(s, indent + "  ", v.my_health);
    s << indent << "is_hit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_hit);
    s << indent << "which_armor_hit: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.which_armor_hit);
    s << indent << "last_hit_time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.last_hit_time);
    s << indent << "has_buff: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_buff);
    s << indent << "buff_left: ";
    Printer<int32_t>::stream(s, indent + "  ", v.buff_left);
    s << indent << "ammo: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ammo);
    s << indent << "my_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.my_pose);
    s << indent << "enemy_pose1: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.enemy_pose1);
    s << indent << "enemy_pose2: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.enemy_pose2);
    s << indent << "how_many_enemies_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.how_many_enemies_detected);
    s << indent << "is_enemy_1_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_enemy_1_detected);
    s << indent << "is_enemy_2_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_enemy_2_detected);
    s << indent << "locked_on_enemy: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.locked_on_enemy);
    s << indent << "enemy_priority: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enemy_priority);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "current_behavior_style: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_behavior_style);
    s << indent << "current_behavior_process: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_behavior_process);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_BLACKBOARDGENERALINFORESPONSE_H
