// Generated by gencpp from file icra_roboin_msgs/ConfirmHit.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_CONFIRMHIT_H
#define ICRA_ROBOIN_MSGS_MESSAGE_CONFIRMHIT_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/ConfirmHitRequest.h>
#include <icra_roboin_msgs/ConfirmHitResponse.h>


namespace icra_roboin_msgs
{

struct ConfirmHit
{

typedef ConfirmHitRequest Request;
typedef ConfirmHitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ConfirmHit
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::ConfirmHit > {
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::icra_roboin_msgs::ConfirmHit&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::ConfirmHit > {
  static const char* value()
  {
    return "icra_roboin_msgs/ConfirmHit";
  }

  static const char* value(const ::icra_roboin_msgs::ConfirmHit&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::ConfirmHitRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::ConfirmHit > 
template<>
struct MD5Sum< ::icra_roboin_msgs::ConfirmHitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::ConfirmHit >::value();
  }
  static const char* value(const ::icra_roboin_msgs::ConfirmHitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::ConfirmHitRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::ConfirmHit > 
template<>
struct DataType< ::icra_roboin_msgs::ConfirmHitRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::ConfirmHit >::value();
  }
  static const char* value(const ::icra_roboin_msgs::ConfirmHitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::ConfirmHitResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::ConfirmHit > 
template<>
struct MD5Sum< ::icra_roboin_msgs::ConfirmHitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::ConfirmHit >::value();
  }
  static const char* value(const ::icra_roboin_msgs::ConfirmHitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::ConfirmHitResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::ConfirmHit > 
template<>
struct DataType< ::icra_roboin_msgs::ConfirmHitResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::ConfirmHit >::value();
  }
  static const char* value(const ::icra_roboin_msgs::ConfirmHitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_CONFIRMHIT_H
