// Generated by gencpp from file icra_roboin_msgs/GoalDescription.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_GOALDESCRIPTION_H
#define ICRA_ROBOIN_MSGS_MESSAGE_GOALDESCRIPTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace icra_roboin_msgs
{
template <class ContainerAllocator>
struct GoalDescription_
{
  typedef GoalDescription_<ContainerAllocator> Type;

  GoalDescription_()
    : header()
    , x(0.0)
    , y(0.0)
    , yaw(0.0)
    , xa(0.0)
    , ya(0.0)
    , yawa(0.0)
    , etc(0.0)  {
    }
  GoalDescription_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , x(0.0)
    , y(0.0)
    , yaw(0.0)
    , xa(0.0)
    , ya(0.0)
    , yawa(0.0)
    , etc(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _xa_type;
  _xa_type xa;

   typedef double _ya_type;
  _ya_type ya;

   typedef double _yawa_type;
  _yawa_type yawa;

   typedef double _etc_type;
  _etc_type etc;





  typedef boost::shared_ptr< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> const> ConstPtr;

}; // struct GoalDescription_

typedef ::icra_roboin_msgs::GoalDescription_<std::allocator<void> > GoalDescription;

typedef boost::shared_ptr< ::icra_roboin_msgs::GoalDescription > GoalDescriptionPtr;
typedef boost::shared_ptr< ::icra_roboin_msgs::GoalDescription const> GoalDescriptionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_roboin_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'icra_roboin_msgs': ['/home/kimtaehan/Desktop/lets_go_canada/src/icra_roboin_msgs/msg', '/home/kimtaehan/Desktop/lets_go_canada/devel/share/icra_roboin_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "245d250014695050d5f8815bfc401e15";
  }

  static const char* value(const ::icra_roboin_msgs::GoalDescription_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x245d250014695050ULL;
  static const uint64_t static_value2 = 0xd5f8815bfc401e15ULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_roboin_msgs/GoalDescription";
  }

  static const char* value(const ::icra_roboin_msgs::GoalDescription_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
float64 x\n\
float64 y\n\
float64 yaw\n\
float64 xa\n\
float64 ya\n\
float64 yawa\n\
float64 etc\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::icra_roboin_msgs::GoalDescription_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.xa);
      stream.next(m.ya);
      stream.next(m.yawa);
      stream.next(m.etc);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GoalDescription_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_roboin_msgs::GoalDescription_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "xa: ";
    Printer<double>::stream(s, indent + "  ", v.xa);
    s << indent << "ya: ";
    Printer<double>::stream(s, indent + "  ", v.ya);
    s << indent << "yawa: ";
    Printer<double>::stream(s, indent + "  ", v.yawa);
    s << indent << "etc: ";
    Printer<double>::stream(s, indent + "  ", v.etc);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_GOALDESCRIPTION_H
