// Generated by gencpp from file icra_roboin_msgs/RefereeShoot.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_REFEREESHOOT_H
#define ICRA_ROBOIN_MSGS_MESSAGE_REFEREESHOOT_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/RefereeShootRequest.h>
#include <icra_roboin_msgs/RefereeShootResponse.h>


namespace icra_roboin_msgs
{

struct RefereeShoot
{

typedef RefereeShootRequest Request;
typedef RefereeShootResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RefereeShoot
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeShoot > {
  static const char* value()
  {
    return "e5d6900e0dd94f9bda0c89e5f1af2cd8";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeShoot&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::RefereeShoot > {
  static const char* value()
  {
    return "icra_roboin_msgs/RefereeShoot";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeShoot&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeShootRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeShoot > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeShootRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeShoot >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeShootRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeShootRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeShoot > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeShootRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeShoot >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeShootRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeShootResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeShoot > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeShootResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeShoot >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeShootResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeShootResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeShoot > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeShootResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeShoot >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeShootResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_REFEREESHOOT_H
