// Generated by gencpp from file icra_roboin_msgs/RefereeGameState.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_REFEREEGAMESTATE_H
#define ICRA_ROBOIN_MSGS_MESSAGE_REFEREEGAMESTATE_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/RefereeGameStateRequest.h>
#include <icra_roboin_msgs/RefereeGameStateResponse.h>


namespace icra_roboin_msgs
{

struct RefereeGameState
{

typedef RefereeGameStateRequest Request;
typedef RefereeGameStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RefereeGameState
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeGameState > {
  static const char* value()
  {
    return "191c705e7422e4ba0c6776ad9b5cd57f";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeGameState&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::RefereeGameState > {
  static const char* value()
  {
    return "icra_roboin_msgs/RefereeGameState";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeGameState&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeGameStateRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeGameState > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeGameStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeGameState >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeGameStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeGameStateRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeGameState > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeGameStateRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeGameState >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeGameStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeGameStateResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeGameState > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeGameStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeGameState >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeGameStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeGameStateResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeGameState > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeGameStateResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeGameState >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeGameStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_REFEREEGAMESTATE_H
