// Generated by gencpp from file icra_roboin_msgs/RefereePenalty.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_REFEREEPENALTY_H
#define ICRA_ROBOIN_MSGS_MESSAGE_REFEREEPENALTY_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/RefereePenaltyRequest.h>
#include <icra_roboin_msgs/RefereePenaltyResponse.h>


namespace icra_roboin_msgs
{

struct RefereePenalty
{

typedef RefereePenaltyRequest Request;
typedef RefereePenaltyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RefereePenalty
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::RefereePenalty > {
  static const char* value()
  {
    return "83418028df150acdf30477a936df6b73";
  }

  static const char* value(const ::icra_roboin_msgs::RefereePenalty&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::RefereePenalty > {
  static const char* value()
  {
    return "icra_roboin_msgs/RefereePenalty";
  }

  static const char* value(const ::icra_roboin_msgs::RefereePenalty&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::RefereePenaltyRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereePenalty > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereePenaltyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereePenalty >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereePenaltyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereePenaltyRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereePenalty > 
template<>
struct DataType< ::icra_roboin_msgs::RefereePenaltyRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereePenalty >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereePenaltyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::RefereePenaltyResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereePenalty > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereePenaltyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereePenalty >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereePenaltyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereePenaltyResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereePenalty > 
template<>
struct DataType< ::icra_roboin_msgs::RefereePenaltyResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereePenalty >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereePenaltyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_REFEREEPENALTY_H
