// Generated by gencpp from file icra_roboin_msgs/RefereeHit.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_REFEREEHIT_H
#define ICRA_ROBOIN_MSGS_MESSAGE_REFEREEHIT_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/RefereeHitRequest.h>
#include <icra_roboin_msgs/RefereeHitResponse.h>


namespace icra_roboin_msgs
{

struct RefereeHit
{

typedef RefereeHitRequest Request;
typedef RefereeHitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RefereeHit
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeHit > {
  static const char* value()
  {
    return "f2c65d4bc3ae1c76b3e2a29cb052e810";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeHit&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::RefereeHit > {
  static const char* value()
  {
    return "icra_roboin_msgs/RefereeHit";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeHit&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeHitRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeHit > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeHitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeHit >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeHitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeHitRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeHit > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeHitRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeHit >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeHitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeHitResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeHit > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeHitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeHit >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeHitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeHitResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeHit > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeHitResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeHit >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeHitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_REFEREEHIT_H
