// Generated by gencpp from file icra_roboin_msgs/RefereeTag.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_REFEREETAG_H
#define ICRA_ROBOIN_MSGS_MESSAGE_REFEREETAG_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/RefereeTagRequest.h>
#include <icra_roboin_msgs/RefereeTagResponse.h>


namespace icra_roboin_msgs
{

struct RefereeTag
{

typedef RefereeTagRequest Request;
typedef RefereeTagResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RefereeTag
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeTag > {
  static const char* value()
  {
    return "e156420e06769c10db65b694db7ee8bc";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeTag&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::RefereeTag > {
  static const char* value()
  {
    return "icra_roboin_msgs/RefereeTag";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeTag&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeTagRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeTag > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeTagRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeTag >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeTagRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeTagRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeTag > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeTagRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeTag >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeTagRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeTagResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeTag > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeTagResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeTag >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeTagResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeTagResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeTag > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeTagResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeTag >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeTagResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_REFEREETAG_H
