// Generated by gencpp from file icra_roboin_msgs/RefereeHitRequest.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_REFEREEHITREQUEST_H
#define ICRA_ROBOIN_MSGS_MESSAGE_REFEREEHITREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace icra_roboin_msgs
{
template <class ContainerAllocator>
struct RefereeHitRequest_
{
  typedef RefereeHitRequest_<ContainerAllocator> Type;

  RefereeHitRequest_()
    : header()
    , damage(0)
    , your_hp(0)
    , which_armor(0)  {
    }
  RefereeHitRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , damage(0)
    , your_hp(0)
    , which_armor(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _damage_type;
  _damage_type damage;

   typedef int16_t _your_hp_type;
  _your_hp_type your_hp;

   typedef uint8_t _which_armor_type;
  _which_armor_type which_armor;





  typedef boost::shared_ptr< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RefereeHitRequest_

typedef ::icra_roboin_msgs::RefereeHitRequest_<std::allocator<void> > RefereeHitRequest;

typedef boost::shared_ptr< ::icra_roboin_msgs::RefereeHitRequest > RefereeHitRequestPtr;
typedef boost::shared_ptr< ::icra_roboin_msgs::RefereeHitRequest const> RefereeHitRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_roboin_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'icra_roboin_msgs': ['/home/kimtaehan/Desktop/lets_go_canada/src/icra_roboin_msgs/msg', '/home/kimtaehan/Desktop/lets_go_canada/devel/share/icra_roboin_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1f02b3a3464db1f137d3ed01d8a1b55";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1f02b3a3464db1fULL;
  static const uint64_t static_value2 = 0x137d3ed01d8a1b55ULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_roboin_msgs/RefereeHitRequest";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
int16 damage\n\
int16 your_hp\n\
\n\
uint8 which_armor\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.damage);
      stream.next(m.your_hp);
      stream.next(m.which_armor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RefereeHitRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_roboin_msgs::RefereeHitRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "damage: ";
    Printer<int16_t>::stream(s, indent + "  ", v.damage);
    s << indent << "your_hp: ";
    Printer<int16_t>::stream(s, indent + "  ", v.your_hp);
    s << indent << "which_armor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.which_armor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_REFEREEHITREQUEST_H
