// Generated by gencpp from file icra_roboin_msgs/RefereeBuff.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_REFEREEBUFF_H
#define ICRA_ROBOIN_MSGS_MESSAGE_REFEREEBUFF_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/RefereeBuffRequest.h>
#include <icra_roboin_msgs/RefereeBuffResponse.h>


namespace icra_roboin_msgs
{

struct RefereeBuff
{

typedef RefereeBuffRequest Request;
typedef RefereeBuffResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RefereeBuff
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeBuff > {
  static const char* value()
  {
    return "226c3dd35a73ae10b2dbbb7a86e3381b";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeBuff&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::RefereeBuff > {
  static const char* value()
  {
    return "icra_roboin_msgs/RefereeBuff";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeBuff&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeBuffRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeBuff > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeBuffRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeBuff >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeBuffRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeBuffRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeBuff > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeBuffRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeBuff >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeBuffRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeBuffResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeBuff > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeBuffResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeBuff >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeBuffResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeBuffResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeBuff > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeBuffResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeBuff >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeBuffResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_REFEREEBUFF_H
