// Generated by gencpp from file icra_roboin_msgs/RefereeReload.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_REFEREERELOAD_H
#define ICRA_ROBOIN_MSGS_MESSAGE_REFEREERELOAD_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/RefereeReloadRequest.h>
#include <icra_roboin_msgs/RefereeReloadResponse.h>


namespace icra_roboin_msgs
{

struct RefereeReload
{

typedef RefereeReloadRequest Request;
typedef RefereeReloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RefereeReload
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeReload > {
  static const char* value()
  {
    return "b6d38dcead6f905c5bce55b773b3d510";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeReload&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::RefereeReload > {
  static const char* value()
  {
    return "icra_roboin_msgs/RefereeReload";
  }

  static const char* value(const ::icra_roboin_msgs::RefereeReload&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeReloadRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeReload > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeReloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeReload >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeReloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeReloadRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeReload > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeReloadRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeReload >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeReloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeReloadResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::RefereeReload > 
template<>
struct MD5Sum< ::icra_roboin_msgs::RefereeReloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::RefereeReload >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeReloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::RefereeReloadResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::RefereeReload > 
template<>
struct DataType< ::icra_roboin_msgs::RefereeReloadResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::RefereeReload >::value();
  }
  static const char* value(const ::icra_roboin_msgs::RefereeReloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_REFEREERELOAD_H
