// Generated by gencpp from file icra_roboin_msgs/SetEnemyPriority.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_SETENEMYPRIORITY_H
#define ICRA_ROBOIN_MSGS_MESSAGE_SETENEMYPRIORITY_H

#include <ros/service_traits.h>


#include <icra_roboin_msgs/SetEnemyPriorityRequest.h>
#include <icra_roboin_msgs/SetEnemyPriorityResponse.h>


namespace icra_roboin_msgs
{

struct SetEnemyPriority
{

typedef SetEnemyPriorityRequest Request;
typedef SetEnemyPriorityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEnemyPriority
} // namespace icra_roboin_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::icra_roboin_msgs::SetEnemyPriority > {
  static const char* value()
  {
    return "72dd0dc38964fd2f75bf39766434fbe2";
  }

  static const char* value(const ::icra_roboin_msgs::SetEnemyPriority&) { return value(); }
};

template<>
struct DataType< ::icra_roboin_msgs::SetEnemyPriority > {
  static const char* value()
  {
    return "icra_roboin_msgs/SetEnemyPriority";
  }

  static const char* value(const ::icra_roboin_msgs::SetEnemyPriority&) { return value(); }
};


// service_traits::MD5Sum< ::icra_roboin_msgs::SetEnemyPriorityRequest> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::SetEnemyPriority > 
template<>
struct MD5Sum< ::icra_roboin_msgs::SetEnemyPriorityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::SetEnemyPriority >::value();
  }
  static const char* value(const ::icra_roboin_msgs::SetEnemyPriorityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::SetEnemyPriorityRequest> should match 
// service_traits::DataType< ::icra_roboin_msgs::SetEnemyPriority > 
template<>
struct DataType< ::icra_roboin_msgs::SetEnemyPriorityRequest>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::SetEnemyPriority >::value();
  }
  static const char* value(const ::icra_roboin_msgs::SetEnemyPriorityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::icra_roboin_msgs::SetEnemyPriorityResponse> should match 
// service_traits::MD5Sum< ::icra_roboin_msgs::SetEnemyPriority > 
template<>
struct MD5Sum< ::icra_roboin_msgs::SetEnemyPriorityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::icra_roboin_msgs::SetEnemyPriority >::value();
  }
  static const char* value(const ::icra_roboin_msgs::SetEnemyPriorityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::icra_roboin_msgs::SetEnemyPriorityResponse> should match 
// service_traits::DataType< ::icra_roboin_msgs::SetEnemyPriority > 
template<>
struct DataType< ::icra_roboin_msgs::SetEnemyPriorityResponse>
{
  static const char* value()
  {
    return DataType< ::icra_roboin_msgs::SetEnemyPriority >::value();
  }
  static const char* value(const ::icra_roboin_msgs::SetEnemyPriorityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_SETENEMYPRIORITY_H
