// Generated by gencpp from file icra_roboin_msgs/SetGoal_2Request.msg
// DO NOT EDIT!


#ifndef ICRA_ROBOIN_MSGS_MESSAGE_SETGOAL_2REQUEST_H
#define ICRA_ROBOIN_MSGS_MESSAGE_SETGOAL_2REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <icra_roboin_msgs/GoalDescription.h>

namespace icra_roboin_msgs
{
template <class ContainerAllocator>
struct SetGoal_2Request_
{
  typedef SetGoal_2Request_<ContainerAllocator> Type;

  SetGoal_2Request_()
    : goal()  {
    }
  SetGoal_2Request_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::icra_roboin_msgs::GoalDescription_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> const> ConstPtr;

}; // struct SetGoal_2Request_

typedef ::icra_roboin_msgs::SetGoal_2Request_<std::allocator<void> > SetGoal_2Request;

typedef boost::shared_ptr< ::icra_roboin_msgs::SetGoal_2Request > SetGoal_2RequestPtr;
typedef boost::shared_ptr< ::icra_roboin_msgs::SetGoal_2Request const> SetGoal_2RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace icra_roboin_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'icra_roboin_msgs': ['/home/kimtaehan/Desktop/lets_go_canada/src/icra_roboin_msgs/msg', '/home/kimtaehan/Desktop/lets_go_canada/devel/share/icra_roboin_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0b503641e6c15140727658d31ee49db3";
  }

  static const char* value(const ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0b503641e6c15140ULL;
  static const uint64_t static_value2 = 0x727658d31ee49db3ULL;
};

template<class ContainerAllocator>
struct DataType< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_roboin_msgs/SetGoal_2Request";
  }

  static const char* value(const ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "icra_roboin_msgs/GoalDescription goal\n\
\n\
================================================================================\n\
MSG: icra_roboin_msgs/GoalDescription\n\
std_msgs/Header header\n\
float64 x\n\
float64 y\n\
float64 yaw\n\
float64 xa\n\
float64 ya\n\
float64 yawa\n\
float64 etc\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGoal_2Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::icra_roboin_msgs::SetGoal_2Request_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::icra_roboin_msgs::GoalDescription_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ICRA_ROBOIN_MSGS_MESSAGE_SETGOAL_2REQUEST_H
