set(_CATKIN_CURRENT_PACKAGE "icra_roboin_vision")
set(icra_roboin_vision_VERSION "1.0.0")
set(icra_roboin_vision_MAINTAINER "RoboMaster <robomaster@dji.com>")
set(icra_roboin_vision_PACKAGE_FORMAT "1")
set(icra_roboin_vision_BUILD_DEPENDS "roscpp" "rospy" "tf" "roborts_msgs" "icra_roboin_msgs" "geometry_msgs")
set(icra_roboin_vision_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "tf" "roborts_msgs" "icra_roboin_msgs" "geometry_msgs")
set(icra_roboin_vision_BUILDTOOL_DEPENDS "catkin")
set(icra_roboin_vision_BUILDTOOL_EXPORT_DEPENDS )
set(icra_roboin_vision_EXEC_DEPENDS "roscpp" "rospy" "tf" "roborts_msgs" "icra_roboin_msgs" "geometry_msgs")
set(icra_roboin_vision_RUN_DEPENDS "roscpp" "rospy" "tf" "roborts_msgs" "icra_roboin_msgs" "geometry_msgs")
set(icra_roboin_vision_TEST_DEPENDS )
set(icra_roboin_vision_DOC_DEPENDS )
set(icra_roboin_vision_URL_WEBSITE "https://github.com/RoboMaster/RoboRTS")
set(icra_roboin_vision_URL_BUGTRACKER "")
set(icra_roboin_vision_URL_REPOSITORY "")
set(icra_roboin_vision_DEPRECATED "")