time stamp
string request_sender
---
time stamp
geometry_msgs/PoseStamped my_pose
geometry_msgs/PoseStamped enemy_pose
geometry_msgs/PoseStamped goal_pose
bool is_enemy_detected
bool has_defense_bonus
int32 defense_time_left
uint8 current_behavior_style
uint8 current_behavior_state

