(cl:in-package icra_roboin_msgs-srv)
(cl:export '(STAMP-VAL
          STAMP
          REQUEST_SENDER-VAL
          REQUEST_SENDER
          CONFIRM-VAL
          CONFIRM
          STAMP-VAL
          STAMP
          TIME_PASSED_FROM_START-VAL
          TIME_PASSED_FROM_START
          GAME_STATE-VAL
          GAME_STATE
          BUFF_ZONE_COOLTIME-VAL
          BUFF_ZONE_COOLTIME
          RELOAD_ZONE_COOLTIME-VAL
          RELOAD_ZONE_COOLTIME
          MY_HEALTH-VAL
          MY_HEALTH
          IS_HIT-VAL
          IS_HIT
          WHICH_ARMOR_HIT-VAL
          WHICH_ARMOR_HIT
          LAST_HIT_TIME-VAL
          LAST_HIT_TIME
          HAS_BUFF-VAL
          HAS_BUFF
          BUFF_LEFT-VAL
          BUFF_LEFT
          AMMO-VAL
          AMMO
          MY_POSE-VAL
          MY_POSE
          ENEMY_POSE1-VAL
          ENEMY_POSE1
          ENEMY_POSE2-VAL
          ENEMY_POSE2
          HOW_MANY_ENEMIES_DETECTED-VAL
          HOW_MANY_ENEMIES_DETECTED
          IS_ENEMY_1_DETECTED-VAL
          IS_ENEMY_1_DETECTED
          IS_ENEMY_2_DETECTED-VAL
          IS_ENEMY_2_DETECTED
          LOCKED_ON_ENEMY-VAL
          LOCKED_ON_ENEMY
          ENEMY_PRIORITY-VAL
          ENEMY_PRIORITY
          GOAL-VAL
          GOAL
          CURRENT_BEHAVIOR_STYLE-VAL
          CURRENT_BEHAVIOR_STYLE
          CURRENT_BEHAVIOR_PROCESS-VAL
          CURRENT_BEHAVIOR_PROCESS
))